:setvar DatabaseName "HospitalManagementDb"

USE [$(DatabaseName)];
GO

SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;

-- These fictional identities are development-only data. Each uses the password
-- DevelopmentOnly!123 and has a PBKDF2 hash generated by ASP.NET Core Identity.
IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'admin@hospital.example')
    INSERT INTO dbo.Users (Email, PasswordHash, Role) VALUES (N'admin@hospital.example', N'AQAAAAIAAYagAAAAEJo/ZkEDQM3+j5v+LdnQ4uzBzttaPDSIfESYSTiVuoYNOdhgkhGv5mvUeaaI6w0HlQ==', 'Administrator');

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'dr.ada@hospital.example')
    INSERT INTO dbo.Users (Email, PasswordHash, Role) VALUES (N'dr.ada@hospital.example', N'AQAAAAIAAYagAAAAEL6YZAw4XwscjJzNE7xkdsH5bpHyjgja7wuKjFlh+5DJB7o8/0UZLi0hrpb2JutNuw==', 'Doctor');

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'dr.sam@hospital.example')
    INSERT INTO dbo.Users (Email, PasswordHash, Role) VALUES (N'dr.sam@hospital.example', N'AQAAAAIAAYagAAAAEPnvPjYqwnZTVYfSthMxqkXsIuzkwGbcHo2R2coT9gKp7y7088m/Sk0RWAZvgdeeqw==', 'Doctor');

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'patient.alex@hospital.example')
    INSERT INTO dbo.Users (Email, PasswordHash, Role) VALUES (N'patient.alex@hospital.example', N'AQAAAAIAAYagAAAAEPf3fCOvQYm4gmwaZgRxu9MOWpnM97HjP0z2V/cOwhXfc07QoJibnyCkXM/uAM5I9w==', 'Patient');

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'staff.jamie@hospital.example')
    INSERT INTO dbo.Users (Email, PasswordHash, Role) VALUES (N'staff.jamie@hospital.example', N'AQAAAAIAAYagAAAAEGIJKaeOrz/Ifqwnryd3I23B2AmsTpNLJ18ZvZYA5spGZDTWbdYx84mzTaoFQmgW3g==', 'Administrator');

IF NOT EXISTS (SELECT 1 FROM dbo.Departments WHERE DepartmentCode = 'CARD')
    INSERT INTO dbo.Departments (DepartmentCode, Name, Description) VALUES ('CARD', N'Cardiology', N'Development cardiology department.');

IF NOT EXISTS (SELECT 1 FROM dbo.Departments WHERE DepartmentCode = 'GEN')
    INSERT INTO dbo.Departments (DepartmentCode, Name, Description) VALUES ('GEN', N'General Medicine', N'Development general medicine department.');

DECLARE @cardiologyDepartmentId int = (SELECT DepartmentId FROM dbo.Departments WHERE DepartmentCode = 'CARD');
DECLARE @generalMedicineDepartmentId int = (SELECT DepartmentId FROM dbo.Departments WHERE DepartmentCode = 'GEN');
DECLARE @adaUserId int = (SELECT UserId FROM dbo.Users WHERE Email = N'dr.ada@hospital.example');
DECLARE @samUserId int = (SELECT UserId FROM dbo.Users WHERE Email = N'dr.sam@hospital.example');
DECLARE @patientUserId int = (SELECT UserId FROM dbo.Users WHERE Email = N'patient.alex@hospital.example');
DECLARE @staffUserId int = (SELECT UserId FROM dbo.Users WHERE Email = N'staff.jamie@hospital.example');

IF NOT EXISTS (SELECT 1 FROM dbo.Doctors WHERE LicenseNumber = 'DEV-LIC-1001')
    INSERT INTO dbo.Doctors (UserId, DepartmentId, LicenseNumber, FirstName, LastName, Specialization, PhoneNumber, ConsultationFee)
    VALUES (@adaUserId, @cardiologyDepartmentId, 'DEV-LIC-1001', N'Ada', N'Khan', N'Cardiology', '555-0101', 1500.00);

IF NOT EXISTS (SELECT 1 FROM dbo.Doctors WHERE LicenseNumber = 'DEV-LIC-1002')
    INSERT INTO dbo.Doctors (UserId, DepartmentId, LicenseNumber, FirstName, LastName, Specialization, PhoneNumber, ConsultationFee)
    VALUES (@samUserId, @generalMedicineDepartmentId, 'DEV-LIC-1002', N'Sam', N'Rao', N'General Medicine', '555-0102', 1000.00);

IF NOT EXISTS (SELECT 1 FROM dbo.Patients WHERE MedicalRecordNumber = 'DEV-MRN-0001')
    INSERT INTO dbo.Patients (UserId, MedicalRecordNumber, FirstName, LastName, DateOfBirth, Gender, PhoneNumber)
    VALUES (@patientUserId, 'DEV-MRN-0001', N'Alex', N'Taylor', '1990-01-15', 'Undisclosed', '555-0103');

IF NOT EXISTS (SELECT 1 FROM dbo.Staff WHERE EmployeeNumber = 'DEV-EMP-0001')
    INSERT INTO dbo.Staff (UserId, DepartmentId, EmployeeNumber, FirstName, LastName, JobTitle, PhoneNumber)
    VALUES (@staffUserId, @generalMedicineDepartmentId, 'DEV-EMP-0001', N'Jamie', N'Lee', N'Reception Coordinator', '555-0104');

COMMIT TRANSACTION;
GO
